phpmyadmin:
  image: viljaste/phpmyadmin:latest
  hostname: phpmyadmin
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - phpmyadmindata
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=300
    - PROTOCOLS=https
    - USERNAME=root
    - PASSWORD=root
phpmyadmindata:
  image: viljaste/data:latest
  hostname: phpmyadmindata
  volumes:
    - /phpmyadmin
