phpmyadmin:
  image: dockerizedrupal/phpmyadmin:1.0.9
  hostname: phpmyadmin
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - phpmyadmin-data
  environment:
    - SERVER_NAME=localhost
    - TIMEZONE=Etc/UTC
    - PROTOCOLS=https,http
    - MYSQL_HOST=
    - MYSQL_PORT=3306
    - MYSQL_USERNAME=container
    - MYSQL_PASSWORD=container
    - PHP_INI_MAX_EXECUTION_TIME=900
    - HTTP_BASIC_AUTH_USERNAME=container
    - HTTP_BASIC_AUTH_PASSWORD=
phpmyadmin-data:
  image: dockerizedrupal/data:1.0.3
  hostname: phpmyadmin-data
  volumes:
    - /phpmyadmin
