phpmyadmin:
  image: dockerizedrupal/phpmyadmin:latest
  hostname: phpmyadmin
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - phpmyadmin-data
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=300
    - PROTOCOLS=https,http
    - USERNAME=root
    - PASSWORD=root
phpmyadmin-data:
  image: dockerizedrupal/data:latest
  hostname: phpmyadmin-data
  volumes:
    - /phpmyadmin
